name: training_env

channels:
  - conda-forge/label/cf201901 #for gdal
  - conda-forge
  - defaults
  - anaconda
  - conda-forge/label/broken

dependencies:
  - python=3.6
  - gdal>=2.3.3
  - pip=20.*
  - shapely>=1.6.1
  - opencv>=3.1.0
  - ipykernel
  - pandas>=0.20
  - anaconda::tensorflow-gpu>=2.0.0
  - seaborn
  - scikit-learn>=0.23
  - scipy
  - cudnn
  - notebook
  - pip :
      - geojson==2.5.0
      - buzzard==0.6.0
      - click
      - ruamel.yaml
      - tensorflow-estimator==2.1.*
      - jupyter-tensorboard
      - joblib

